export const WALLET_STORAGE_KEYS = {
  activeCurrency: 'finapp-wallets-active-currency',
  activeType: 'finapp-wallets-active-type',
  groupedBy: 'finapp-wallets-groupedBy',
  groupedBySecondary: 'finapp-wallets-groupedBySecondary',
  includeArchivedInStats: 'finapp-wallets-include-archived-in-stats',
  includeExcludedInStats: 'finapp-wallets-include-excluded-in-stats',
  selectorCurrency: 'finapp-wallets-selector-currency',
  selectorGroupedBy: 'finapp-wallets-selector-groupedBy',
  selectorToggleMap: 'finapp-wallets-selector-toggle-map',
  showArchived: 'finapp-wallets-show-archived',
  showStatistics: 'finapp-wallets-show-statistics',
  sortOrders: 'finapp-wallets-sort-orders',
  toggleMap: 'finapp-wallets-toggle-map',
  totalPrefix: 'finapp-wallets-total-',
} as const
