packages:
  - app
  - docs
allowBuilds:
  '@journeyapps/wa-sqlite': set this to true or false
  '@parcel/watcher': set this to true or false
  better-sqlite3: set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
  vue-demi: set this to true or false
overrides:
  fast-uri@<=3.1.0: '>=3.1.1'
  fast-uri@<=3.1.1: '>=3.1.2'
  hono@<4.12.18: '>=4.12.18'
  ip-address@<=10.1.0: '>=10.1.1'
  serialize-javascript@<7.0.5: '>=7.0.5'
  serialize-javascript@<=7.0.2: '>=7.0.3'
