<script setup lang="ts">
import { useInitApp } from '~/components/app/useInitApp'
import { useCategoriesStore } from '~/components/categories/useCategoriesStore'
import { useDemo } from '~/components/demo/useDemo'
import { useMenuData } from '~/components/layout/useMenuData'
import { useSearch } from '~/components/search/useSearch'
import { useTrnsFormStore } from '~/components/trnForm/useTrnsFormStore'
import { useTrnsStore } from '~/components/trns/useTrnsStore'
import { useUserStore } from '~/components/user/useUserStore'
import { useWalletsStore } from '~/components/wallets/useWalletsStore'

const keepalive = ['Categories', 'CategoriesId', 'Wallets', 'WalletsId', 'Dashboard']

const categoriesStore = useCategoriesStore()
const trnsFormStore = useTrnsFormStore()
const userStore = useUserStore()
const walletsStore = useWalletsStore()
const trnsStore = useTrnsStore()
const { isDemo } = useDemo()
const { isMenuOpen } = useMenuData()
const { isSearchOpen } = useSearch()
const { loadDataFromCache, loadDataFromDB } = useInitApp()
const { width } = useWindowSize()

const isShowSidebar = useCookie('finapp.isShowSidebar', { default: () => true })
const isOnboardedHint = useCookie('finapp.isOnboarded', { default: () => false })
const isOnboarded = computed(() => walletsStore.hasItems && categoriesStore.hasItems && trnsStore.hasItems)
watch(isOnboarded, val => (isOnboardedHint.value = val))

const hasSidebar = computed(() => isOnboardedHint.value || isOnboarded.value)
const layoutClasses = computed(() => cn(
  'flex min-h-dvh flex-col transition-all duration-300 ease-in-out',
  hasSidebar.value && (isShowSidebar.value ? 'md:pl-72' : 'md:pl-12'),
  isOnboarded.value && trnsFormStore.ui.isShow && 'md:pr-[360px]',
))

const { error, status } = useAsyncData(
  'app',
  async () => {
    if (isDemo.value) {
      // Skip cache load if stores already have data (just generated by openDemo)
      if (!categoriesStore.hasItems)
        await loadDataFromCache()
    }
    else if (userStore.currentUser || hasAuthCookie()) {
      await loadDataFromCache()

      if (navigator.onLine) {
        // If cache had data, load from DB in background (user sees cached UI).
        // If no cache (first login), await so the loading screen stays visible.
        if (isOnboarded.value)
          loadDataFromDB()
        else
          await loadDataFromDB()
      }
    }
  },
)

defineShortcuts({
  'escape': () => {
    if (trnsFormStore.ui.isShow)
      trnsFormStore.ui.isShow = false
  },
  'meta_\\': () => {
    isShowSidebar.value = !isShowSidebar.value
  },
  'meta_g': () => {
    trnsFormStore.ui.isShow
      ? trnsFormStore.ui.isShow = false
      : trnsFormStore.openFormForCreate()
  },
  'meta_k': () => {
    isSearchOpen.value = !isSearchOpen.value
  },
})
</script>

<template>
  <div
    :class="layoutClasses"
    style="margin-left: env(safe-area-inset-left)"
  >
    <div v-if="status === 'pending' && !isOnboardedHint" class="flex-center h-dvh">
      <UiLogo size="lg" />
    </div>

    <div v-else-if="status === 'error'" class="p-4">
      <pre>{{ error }}</pre>
    </div>

    <template v-else-if="status === 'success'">
      <template v-if="isOnboarded">
        <LayoutSidebar
          :isShowSidebar
          @toggleSidebar="isShowSidebar = !isShowSidebar"
        />
      </template>

      <div :class="isOnboarded ? 'flex min-h-dvh flex-col md:py-4 md:pr-4' : 'flex flex-1 items-center justify-center'">
        <div :class="isOnboarded ? 'bg-default md:border-item-4 relative z-10 flex max-w-5xl flex-1 flex-col contain-paint md:rounded-md md:border lg:rounded-2xl' : 'w-full max-w-lg px-4'">
          <main
            id="pageScroll"
            :style="isOnboarded ? 'padding-bottom: calc(64px + env(safe-area-inset-bottom))' : ''"
            class="@container/main flex-1 contain-paint md:!pb-0"
          >
            <slot :keepalive="{ include: keepalive }" />
          </main>
        </div>
      </div>

      <SearchModal v-if="isOnboarded" />

      <template v-if="isOnboarded">
        <TrnFormFloatOpener v-if="width >= 767" />

        <LayoutMenuBottom />
        <LayoutMenuBottomModal v-if="isMenuOpen" @close="isMenuOpen = false" />
      </template>
    </template>

    <Teleport
      v-if="categoriesStore.hasItems && walletsStore.hasItems"
      to="body"
    >
      <TrnFormBottom v-if="width < 767" />
      <TrnFormSidebar v-if="width >= 767" />
    </Teleport>
  </div>
</template>
