import type { Categories } from '~/components/categories/types'
import type { Wallets } from '~/components/wallets/types'

const data: {
  categories: Categories
  wallets: Wallets
} = {
  categories: {
    '4b6473ee7324': {
      color: '#d84315',
      editedAt: 1585408887791,
      icon: 'mdi:pill',
      name: 'Health',
      order: 8,
      parentId: 0,
      showInLastUsed: true,
      showInQuickSelector: false,
    },
    '06ca25500ef2': {
      color: '#4fc3f7',
      editedAt: 1585408861256,
      icon: 'mdi:airplane',
      name: 'Travel',
      order: 11,
      parentId: 0,
      showInLastUsed: true,
      showInQuickSelector: false,
    },
    'd564ed02cf7f': {
      color: '#8bc34a',
      editedAt: 1585408861256,
      icon: 'mdi:human-male',
      name: 'Freelance',
      order: 9,
      parentId: 0,
      showInLastUsed: true,
      showInQuickSelector: false,
    },
    'KsNnR1EDBl9tAZTaWUP': {
      color: '#90a4ae',
      editedAt: 1585408861252,
      icon: 'mdi:car-sports',
      name: 'Auto',
      order: 0,
      parentId: 0,
      showInLastUsed: true,
      showInQuickSelector: false,
    },
    'KsNnRB3MqKvAqwo5IEf': {
      color: '#d4e157',
      editedAt: 1585073319837,
      icon: 'mdi:food',
      name: 'Cafe',
      order: 1,
      parentId: 'KxKMi55aCVkJXsiDE',
      showInLastUsed: true,
      showInQuickSelector: true,
    },
    'KsNnREUqdH4nTGEjEhl': {
      color: '#ba68c8',
      editedAt: 1585408861253,
      icon: 'mdi:account-heart',
      name: 'Family',
      order: 1,
      parentId: 0,
      showInLastUsed: true,
      showInQuickSelector: false,
    },
    'KsNnRHjakWM4imFmCpI': {
      color: '#d4e157',
      editedAt: 1584359067144,
      icon: 'mdi:food-apple',
      name: 'Groceries',
      order: 2,
      parentId: 'KxKMi55aCVkJXsiDE',
      showInLastUsed: true,
    },
    'KsNnS6QgcjgSVeA3KaM': {
      color: '#90a4ae',
      editedAt: 1584359067348,
      icon: 'mdi:gas-station',
      name: 'Gas',
      parentId: 'KsNnR1EDBl9tAZTaWUP',
      showInLastUsed: true,
      showInQuickSelector: true,
    },
    'KsNnSMR4DtZXFr75V2Y': {
      color: '#8d6e63',
      editedAt: 1585078567615,
      icon: 'mdi:fire',
      name: 'Gas',
      parentId: 'KsNnTR_IP7TZ5UQ39MV',
      showInLastUsed: false,
      showInQuickSelector: false,
    },
    'KsNnSzI9bi2L6YtJpFl': {
      color: '#90a4ae',
      editedAt: 1585078593530,
      icon: 'mdi:cogs',
      name: 'Spare parts',
      parentId: 'KsNnR1EDBl9tAZTaWUP',
      showInLastUsed: true,
      showInQuickSelector: false,
    },
    'KsNnT85ujLHZFMRjqau': {
      color: '#8d6e63',
      editedAt: 1585078530426,
      icon: 'mdi:microsoft-internet-explorer',
      name: 'Internet',
      parentId: 'KsNnTR_IP7TZ5UQ39MV',
      showInLastUsed: true,
      showInQuickSelector: false,
    },
    'KsNnTR_IP7TZ5UQ39MV': {
      color: '#8d6e63',
      editedAt: 1585408861254,
      icon: 'mdi:home-currency-usd',
      name: 'Home pay',
      order: 2,
      parentId: 0,
      showInLastUsed: false,
      showInQuickSelector: false,
    },
    'KsNnUCHgx-3TJVpEOo5': {
      color: '#8d6e63',
      editedAt: 1585078546884,
      icon: 'mdi:toilet',
      name: 'Water',
      parentId: 'KsNnTR_IP7TZ5UQ39MV',
      showInLastUsed: false,
      showInQuickSelector: false,
    },
    'KsNnUVvhaCBzUOIce-c': {
      color: '#ff8a65',
      editedAt: 1585408861256,
      icon: 'mdi:account-tie',
      name: 'Office',
      order: 10,
      parentId: 0,
      showInLastUsed: true,
      showInQuickSelector: false,
    },
    'KsNnVKle-reg5skNcxE': {
      color: '#26a69a',
      editedAt: 1585408861254,
      icon: 'mdi:cellphone-android',
      name: 'Phone',
      order: 5,
      parentId: 0,
      showInLastUsed: true,
      showInQuickSelector: false,
    },
    'KsNnVRQvYywN2OZFrEq': {
      color: '#1b5e20',
      editedAt: 1585408861255,
      icon: 'mdi:vuejs',
      name: 'Vuejs',
      order: 6,
      parentId: 0,
      showInLastUsed: true,
    },
    'KsNnVUo-gQZCYr_Tqjx': {
      color: '#f48fb1',
      editedAt: 1585408875803,
      icon: 'mdi:badminton',
      name: 'Sport',
      order: 7,
      parentId: 0,
      showInLastUsed: true,
      showInQuickSelector: false,
    },
    'KxKMi55aCVkJXsiDE': {
      color: '#d4e157',
      editedAt: 1585408895295,
      icon: 'mdi:cupcake',
      name: 'Food',
      order: 4,
      parentId: 0,
      showInLastUsed: true,
      showInQuickSelector: false,
    },
  },

  wallets: {
    '200921_FltN3F': {
      color: '#1565c0',
      currency: 'RUB',
      desc: '',
      editedAt: 1585408895295,
      isWithdrawal: true,
      name: 'Rubles Cash',
      order: 4,
      type: 'cash',
    },
    '200921_WrAFwe': {
      color: '#ef5350',
      currency: 'USD',
      desc: '',
      editedAt: 1585408895295,
      isWithdrawal: true,
      name: 'USD',
      order: 10,
      type: 'cash',
    },
    '210614_uvi9w8': {
      color: '#ad1457',
      currency: 'USD',
      desc: 'Money for study',
      editedAt: 1585408895295,
      isWithdrawal: true,
      name: 'Study',
      order: 9,
      type: 'cash',
    },
    '220315_p78836': {
      color: '#388e3c',
      currency: 'USD',
      desc: 'Money for party',
      editedAt: 1585408895295,
      isArchived: true,
      isWithdrawal: true,
      name: 'Party',
      order: 25,
      type: 'cashless',
    },
    '231223_x83sls': {
      color: '#1565c0',
      currency: 'RUB',
      desc: 'Money for auto',
      editedAt: 1585408895295,
      isWithdrawal: true,
      name: 'Auto',
      order: 3,
      type: 'cash',
    },
    '240324_3zjma5': {
      color: '#d32f2f',
      creditLimit: 160000,
      currency: 'RUB',
      desc: 'Money for office',
      editedAt: 1585408895295,
      name: 'Credit Card',
      order: 1,
      type: 'credit',
    },
  },
}

export default data
