import { z } from 'zod/v4'

import type { CategoryId, CategoryItem } from '~/components/categories/types'
import type { WalletId, WalletItem } from '~/components/wallets/types'

export enum TrnType {
  Expense = 0,
  Income = 1,
  Transfer = 2,
}

export type TrnId = string

export function getTrnTypeByAmount(amount: number): TrnType {
  return amount > 0 ? TrnType.Income : TrnType.Expense
}

export type TrnsViewType = 'adjustment' | 'all' | 'expense' | 'income' | 'transfer'

export type TransferSide = 'expense' | 'income'

const baseTrnSchema = z.object({
  // Civil day (UTC-midnight ms-epoch); the bucketing truth. See plans/civil-date-migration.md.
  date: z.number(),
  desc: z.string().optional(),
  // Original entry instant (ms-epoch); audit/ordering only, never used for bucketing.
  enteredAt: z.number().optional(),
  // Set when this trn was generated by / confirmed for a recurrence rule (plans/recurrences.md).
  recurrenceId: z.string().optional(),
  updatedAt: z.number(),
})

const transactionSchema = baseTrnSchema.extend({
  amount: z.number().positive(),
  categoryId: z.string().min(1),
  type: z.union([z.literal(TrnType.Expense), z.literal(TrnType.Income)]),
  walletId: z.string().min(1),
})

const transferSchema = baseTrnSchema.extend({
  categoryId: z.literal('transfer'),
  expenseAmount: z.number().positive(),
  expenseWalletId: z.string().min(1),
  incomeAmount: z.number().positive(),
  incomeWalletId: z.string().min(1),
  type: z.literal(TrnType.Transfer),
})

export const trnItemSchema = z.discriminatedUnion('type', [
  transactionSchema,
  transferSchema,
])

export type Transaction = z.infer<typeof transactionSchema>
export type Transfer = z.infer<typeof transferSchema>
export type TrnItem = z.infer<typeof trnItemSchema>
type TrnItemFullBase = {
  category: CategoryItem
  categoryParent?: CategoryItem
  id: TrnId
}

export type TransactionFull = Transaction & TrnItemFullBase & {
  wallet: WalletItem
}

export type TransferFull = Transfer & TrnItemFullBase & {
  expenseWallet: WalletItem
  incomeWallet: WalletItem
}

export type TrnItemFull = TransactionFull | TransferFull

export function isTransfer(trn: TrnItem | TrnItemFull | undefined): trn is Transfer | TransferFull {
  return trn?.type === TrnType.Transfer
}

export type Trns = Record<TrnId, TrnItem>

export type TrnsGetterProps = {
  categoriesIds?: CategoryId[]
  dates?: {
    end: number
    start: number
  }
  sort?: boolean
  trnsIds?: TrnId[]
  trnsItems?: Trns
  trnsTypes?: TrnType[]
  walletsIds?: WalletId[]
}

export type TrnFormValues = {
  // [transaction, expenseTransfer, incomeTransfer]
  amount: [number, number, number]
  // [transaction, expenseTransfer, incomeTransfer]
  amountRaw: [string, string, string]

  categoryId: CategoryId | null
  date: number
  desc?: string
  expenseWalletId: WalletId | null
  incomeWalletId: WalletId | null
  transferType: TransferSide
  trnId: null | TrnId

  trnType: TrnType
  walletId: WalletId | null
}
